// Imposter question pairs.
// Each pair = [questionA, questionB]. The host randomly picks which is "common"
// (sent to non-imposters) and which is "imposter" (sent only to the imposter).
// The two questions in a pair should overlap enough that answers can plausibly
// fit either, so the imposter has a chance to bluff.

export const QUESTION_PAIRS = [
  // ---------- Favorites & food ----------
  ["What's your favorite pizza topping?", "What's your favorite burger topping?"],
  ["What's your favorite ice cream flavor?", "What's your favorite milkshake flavor?"],
  ["Name a fruit you'd put in a smoothie", "Name a fruit you'd put in a fruit salad"],
  ["What's the best fast food chain?", "What's the best fast food side?"],
  ["What's your go-to comfort food?", "What's your go-to hangover food?"],
  ["What's the best breakfast food?", "What's the best brunch food?"],
  ["What's your favorite candy?", "What's your favorite chocolate bar?"],
  ["What's a snack you'd take to a movie?", "What's a snack you'd take to a party?"],
  ["What's the best soda?", "What's the best juice?"],
  ["Best alcoholic drink?", "Best mixer for a drink?"],
  ["Best beer?", "Best cocktail?"],
  ["Best wine for a date?", "Best wine for a party?"],
  ["Best shot to take?", "Worst shot to take?"],
  ["What's the best dessert?", "What's the best birthday cake flavor?"],
  ["What's the best pasta dish?", "What's the best pasta sauce?"],
  ["What's your favorite cereal?", "What's your favorite breakfast?"],
  ["Best pizza chain?", "Best burger chain?"],
  ["Best coffee order?", "Best Starbucks drink?"],
  ["Best chip flavor?", "Best Doritos flavor?"],
  ["Best topping for popcorn?", "Best topping for nachos?"],
  ["Best sandwich?", "Best deli order?"],
  ["Best taco filling?", "Best burrito filling?"],
  ["Best ice cream topping?", "Best frozen yogurt topping?"],
  ["Best snack at 3 AM?", "Worst snack at 3 AM?"],
  ["Best snack to share?", "Worst snack to share?"],
  ["Best fast food order at 2am?", "Best fast food order at noon?"],
  ["Most overrated drink?", "Most underrated drink?"],
  ["Most overrated food?", "Most underrated food?"],
  ["Best food to eat in bed?", "Worst food to eat in bed?"],
  ["What's a weird food combo that actually slaps?", "What's a weird food combo that sounds gross?"],

  // ---------- Favorites & lifestyle ----------
  ["What's your favorite color?", "What's your favorite color to wear?"],
  ["What's your favorite season?", "What's your favorite holiday?"],
  ["Best month of the year?", "Worst month of the year?"],
  ["Best day of the week?", "Worst day of the week?"],
  ["What's your dream car?", "What's your dream first car?"],
  ["A great hobby?", "A great expensive hobby?"],
  ["Best sport to play?", "Best sport to watch?"],
  ["Best music genre?", "Best movie genre?"],
  ["Best Disney movie?", "Best Pixar movie?"],
  ["Best Marvel movie?", "Best DC movie?"],
  ["Best show to binge?", "Best show to watch with family?"],
  ["Best dream vacation?", "Best honeymoon spot?"],
  ["Best city to visit?", "Best city to live in?"],
  ["Your dream job?", "Your backup dream job?"],
  ["A job you'd hate?", "A job that would bore you to death?"],
  ["Best holiday movie?", "Best summer movie?"],
  ["Best place to take a date?", "Best place for a first kiss?"],
  ["A great smell?", "A great scent for a candle?"],
  ["Best thing about summer?", "Best thing about winter?"],
  ["Best thing to drink when sick?", "Best thing to eat when sick?"],
  ["Best Halloween costume?", "Best couples Halloween costume?"],
  ["Great gift for a guy?", "Great gift for a girl?"],
  ["Great gift under $20?", "Great gift under $100?"],
  ["Best smell in the morning?", "Best smell in the kitchen?"],
  ["Great party game?", "Great drinking game?"],
  ["Great board game?", "Great card game?"],
  ["Great video game?", "Great mobile game?"],
  ["Best superhero?", "Best supervillain?"],
  ["Best Christmas song?", "Best Christmas movie?"],
  ["Great rainy day activity?", "Great snowy day activity?"],
  ["Great wedding gift?", "Great housewarming gift?"],
  ["Best workout?", "Best home workout?"],
  ["Best background music for a date?", "Best background music for studying?"],
  ["Best song to scream in the car?", "Best song to dance to?"],
  ["A song that gets you hyped?", "A song that makes you cry?"],
  ["Most quotable movie?", "Most quotable show?"],
  ["Best couple in a movie?", "Worst couple in a movie?"],
  ["Best cartoon character?", "Scariest cartoon character?"],
  ["Best villain in a kid's movie?", "Scariest villain in a kid's movie?"],
  ["Best animated show?", "Best kid's TV show?"],
  ["Best video game character?", "Worst video game character?"],

  // ---------- "Who would..." ----------
  ["Who's most likely to go viral?", "Who's most likely to get canceled?"],
  ["Who would survive longest in a zombie apocalypse?", "Who would die first in a zombie apocalypse?"],
  ["Who's most likely to start a cult?", "Who's most likely to join a cult?"],
  ["Who's most likely to become a millionaire?", "Who's most likely to win the lottery?"],
  ["Who would be the best parent?", "Who would be the worst parent?"],
  ["Who would win in a fist fight?", "Who would start a bar fight?"],
  ["Who's most likely to ghost you?", "Who's most likely to overshare?"],
  ["Who has the worst taste in music?", "Who has the worst taste in clothes?"],
  ["Who's the funniest in this room?", "Who's the loudest in this room?"],
  ["Who's the best dancer?", "Who's the best singer?"],
  ["Who would be the best wingman?", "Who would be the best therapist?"],
  ["Who's most likely to get arrested?", "Who's most likely to talk their way out of an arrest?"],
  ["Who would survive prison best?", "Who would last 5 minutes in prison?"],
  ["Who's the worst driver?", "Who's the most aggressive driver?"],
  ["Who's the messiest?", "Who's the cleanest?"],
  ["Who's most likely to text their ex at 2am?", "Who's most likely to drunk-call their ex?"],
  ["Who's most likely to get a tattoo they regret?", "Who's most likely to get a piercing they regret?"],
  ["Who'd be the best at karaoke?", "Who'd be the worst at karaoke?"],
  ["Who's most likely to become famous?", "Who's most likely to become infamous?"],
  ["Who would survive being stranded on an island?", "Who would lose their mind first on a deserted island?"],
  ["Who's most likely to fake an injury?", "Who's most likely to actually injure themselves?"],
  ["Who's the best cook?", "Who's the worst cook?"],
  ["Who's most likely to forget your birthday?", "Who's most likely to overcelebrate your birthday?"],
  ["Who'd be the best teacher?", "Who'd be the worst teacher?"],
  ["Who's most likely to start an OnlyFans?", "Who's most likely to subscribe to one?"],
  ["Who's most likely to get scammed?", "Who's most likely to BE the scammer?"],
  ["Who's most likely to fall down stairs?", "Who's most likely to walk into a glass door?"],
  ["Who'd be the most chaotic drunk?", "Who'd be the most emotional drunk?"],
  ["Who's the biggest gossip?", "Who's the biggest snitch?"],
  ["Who's most likely to win a Nobel prize?", "Who's most likely to win a Darwin Award?"],
  ["Who'd be the best secret agent?", "Who'd be the worst secret agent?"],
  ["Who's most likely to host a podcast?", "Who's most likely to be a guest on a podcast?"],
  ["Who's most likely to go bald first?", "Who's most likely to get a terrible haircut?"],
  ["Who's most likely to sleep through their alarm?", "Who's most likely to be late to their own wedding?"],
  ["Who's most likely to get stuck in a chimney?", "Who's most likely to get stuck in an elevator?"],
  ["Who'd be the funniest stand-up comedian?", "Who'd be the worst stand-up comedian?"],
  ["Who's most likely to fight a stranger?", "Who's most likely to befriend a stranger in 5 minutes?"],
  ["Who'd crack first under torture?", "Who'd crack first in a hostage situation?"],
  ["Who's most likely to date a celebrity?", "Who's most likely to stalk a celebrity?"],
  ["Who's most likely to lie about their age?", "Who's most likely to lie about their job?"],
  ["Who'd be the best villain?", "Who'd be the worst villain?"],
  ["Who's most likely to cry at a movie?", "Who's most likely to laugh at a funeral?"],
  ["Who's most likely to win a hot dog eating contest?", "Who's most likely to throw up at one?"],
  ["Who would survive an apocalypse?", "Who would CAUSE an apocalypse?"],
  ["Who's most likely to date their boss?", "Who's most likely to fight their boss?"],
  ["Who's the best at giving advice?", "Who's the best at ignoring advice?"],
  ["Who's most likely to be a reality TV star?", "Who's most likely to get kicked off reality TV?"],
  ["Who's most likely to walk into a pole?", "Who's most likely to trip on a flat surface?"],
  ["Who's most likely to live to 100?", "Who's most likely to live in their parents' basement at 40?"],
  ["Who would win Survivor?", "Who would win The Bachelor/Bachelorette?"],
  ["Who's most likely to become a politician?", "Who's most likely to start a riot?"],
  ["Who'd be the best pirate?", "Who'd be the best wizard?"],
  ["Who's most likely to be a serial killer?", "Who's most likely to be the victim in a true-crime doc?"],
  ["Who's the biggest pushover?", "Who's the biggest control freak?"],
  ["Who'd survive the Hunger Games?", "Who'd snitch first in the Hunger Games?"],
  ["Who's most likely to go to therapy?", "Who's most likely to NEED therapy and refuse?"],
  ["Who's most likely to send a risky text?", "Who's most likely to screenshot a risky text?"],
  ["Who's most likely to get catfished?", "Who's most likely to BE the catfish?"],
  ["Who's most likely to start a fire?", "Who's most likely to put out a fire?"],
  ["Who'd be best in a horror movie?", "Who'd be the comic relief in a horror movie?"],
  ["Who's the worst dancer?", "Who's the most embarrassing to dance with?"],
  ["Who's most likely to eat the weirdest thing on a menu?", "Who's most likely to send their food back?"],

  // ---------- Spicy / inappropriate ----------
  ["What's a turn-on?", "What's a turn-off?"],
  ["What's an attractive trait?", "What's an unattractive trait?"],
  ["Best place to hook up?", "Worst place to hook up?"],
  ["Your biggest red flag?", "Your biggest green flag?"],
  ["Most attractive accent?", "Least attractive accent?"],
  ["Sexiest body part?", "Most underrated body part?"],
  ["Worst pickup line?", "Best pickup line?"],
  ["Best place for a quickie?", "Worst place for a quickie?"],
  ["Sexiest profession?", "Most boring profession?"],
  ["What's hot?", "What's cringe?"],
  ["Best place to take someone home?", "Worst place to take someone home?"],
  ["Deal-breaker on a first date?", "Deal-MAKER on a first date?"],
  ["Most embarrassing thing to be caught doing?", "Most embarrassing thing your parents caught you doing?"],
  ["Worst thing to find in someone's bedroom?", "Best thing to find in someone's bedroom?"],
  ["What's worse than catching feelings?", "What's worse than getting ghosted?"],
  ["Worst place to get a cramp?", "Worst place to get an itch?"],
  ["Worst place to fart?", "Worst place to sneeze?"],
  ["Worst lie to tell on a first date?", "Worst lie to tell to your boss?"],
  ["Worst tattoo idea?", "Worst piercing idea?"],
  ["Most awkward thing to walk in on?", "Most awkward thing to be walked in on doing?"],
  ["Worst place to run out of toilet paper?", "Worst place to throw up?"],
  ["Pickup line that actually worked on you?", "Worst opening message on a dating app?"],
  ["Worst thing to say after sex?", "Worst thing to say BEFORE sex?"],
  ["Worst place to fall asleep?", "Worst place to wake up?"],
  ["Sexiest celebrity?", "Most overrated hot celebrity?"],
  ["Worst thing to find in your food?", "Worst thing to find in your drink?"],
  ["Worst app on your phone?", "Most embarrassing app on your phone?"],
  ["Worst thing to do at a wedding?", "Worst thing to do at a funeral?"],
  ["Most awkward family dinner topic?", "Most awkward Thanksgiving topic?"],
  ["Worst gift to get from your in-laws?", "Worst gift to get from your boss?"],
  ["Worst place to hide a body?", "Worst place to bury treasure?"],
  ["Worst nickname?", "Worst stage name?"],
  ["Worst movie to watch with your parents?", "Worst movie to watch on a first date?"],
  ["Worst kink to admit to?", "Worst kink to discover your partner has?"],
  ["Most embarrassing search history item?", "Most embarrassing autocomplete?"],
  ["Worst thing to say to a cop?", "Worst thing to say to a judge?"],
  ["Worst place to have a panic attack?", "Worst place to have a hangover?"],
  ["Worst thing to do at the gym?", "Worst thing to do at the pool?"],
  ["Worst superpower for a date?", "Worst superpower for a job interview?"],
  ["Worst thing to forget on a trip?", "Worst thing to forget at home?"],
  ["Worst pet to bring on a date?", "Worst pet to bring to work?"],
  ["Most awkward thing to say to your ex?", "Most awkward thing to say to your crush?"],
  ["Worst thing to wear to a wedding?", "Worst thing to wear to a funeral?"],
  ["Most embarrassing way to get dumped?", "Most embarrassing way to dump someone?"],
  ["Worst thing to do drunk?", "Worst thing to do high?"],
  ["Worst thing to find on your partner's phone?", "Worst thing to find in your partner's car?"],
  ["Worst thing about Tinder?", "Worst thing about Hinge?"],
  ["Most overrated sex position?", "Most underrated sex position?"],
  ["Worst place to get aroused?", "Worst place to get caught looking at your phone?"],
  ["Best place to make out?", "Worst place to make out?"],
  ["Worst thing to find in a hookup's apartment?", "Best thing to find in a hookup's apartment?"],
  ["Worst pet name to yell during sex?", "Worst song to play during sex?"],
  ["Most embarrassing thing you've done sober?", "Most embarrassing thing you've done drunk?"],
  ["Worst time to need to poop?", "Worst time to need to pee?"],
  ["Worst thing to admit to your therapist?", "Worst thing to admit to your priest?"],
  ["Best thing about a one-night stand?", "Worst thing about a one-night stand?"],
  ["Worst thing to find in a public bathroom?", "Worst thing to find in a porta-potty?"],
  ["Worst part of a hookup?", "Best part of a hookup?"],
  ["Worst thing to confess to your partner?", "Worst thing to confess to your best friend?"],
  ["Worst kink to admit on a first date?", "Worst kink to admit to your parents?"],
  ["Worst sound during sex?", "Worst smell during sex?"],
  ["Most awkward way to get an erection?", "Most awkward place to get an erection?"],
  ["Worst body part to break?", "Most embarrassing body part to break?"],
  ["Worst place to throw up after drinking?", "Worst place to pass out after drinking?"],
  ["Best part of a no-strings-attached relationship?", "Worst part of a no-strings-attached relationship?"],
  ["Worst dirty talk?", "Best dirty talk?"],
  ["Worst thing to find on your partner's search history?", "Worst thing to find on your partner's text history?"],
  ["Worst Tinder bio you've seen?", "Worst dating profile photo you've seen?"],
  ["Worst place to break up with someone?", "Best place to break up with someone?"],
  ["Worst sext you've ever sent?", "Worst sext you've ever received?"],
  ["What's the ick?", "What's hot but you'd never admit it?"],
  ["Sexiest movie scene?", "Most awkward movie sex scene?"],
  ["Worst body count answer?", "Best body count answer?"],
  ["Worst thing to say during a first kiss?", "Worst thing to do during a first kiss?"],
  ["Sluttiest outfit?", "Most innocent looking outfit?"],
  ["Worst place to be horny?", "Worst place to be hungover?"],
  ["Most awkward boner story?", "Most awkward period story?"],
  ["What does cheating actually count as?", "What does NOT count as cheating?"],
  ["Worst hookup you've ever had?", "Best hookup you've ever had?"],
  ["Worst type of person to date?", "Best type of person to date?"],
  ["Wildest place you've hooked up?", "Tamest place you've hooked up?"],

  // ---------- Would you rather / hypotheticals ----------
  ["A power that sounds cool but isn't?", "A power that sounds lame but is actually amazing?"],
  ["Boring superhero name?", "Scary supervillain name?"],
  ["Worst way to die in a horror movie?", "Funniest way to die in a horror movie?"],
  ["Worst pet to own?", "Best pet for a kid?"],
  ["Best place to hide during hide and seek?", "Worst place to hide during hide and seek?"],
  ["Best fake name to give a stranger?", "Worst fake name to give a stranger?"],
  ["Worst tourist destination?", "Most overrated tourist destination?"],
  ["Most useless app?", "Most addictive app?"],
  ["Best thing about a long flight?", "Worst thing about a long flight?"],
  ["Best thing about being rich?", "Worst thing about being rich?"],
  ["Worst job in the world?", "Most underpaid job?"],
  ["Best thing to do alone?", "Worst thing to do alone?"],
  ["Best dream you've had?", "Worst nightmare you've had?"],
  ["Best lie to tell your boss?", "Worst lie to tell your boss?"],
  ["Best excuse for being late?", "Worst excuse for being late?"],
  ["Most useful kitchen appliance?", "Most useless kitchen appliance?"],
  ["Best thing about being short?", "Best thing about being tall?"],
  ["Worst injury you can get from a sport?", "Most embarrassing injury?"],
  ["Worst thing about getting old?", "Best thing about getting old?"],
  ["Worst smell?", "Best smell?"],
  ["Worst sound in the world?", "Most satisfying sound?"],
  ["Best texture?", "Worst texture?"],
  ["Worst feeling?", "Best feeling?"],
  ["Best way to start a morning?", "Worst way to start a morning?"],
  ["Best way to procrastinate?", "Worst way to procrastinate?"],
  ["Best feature on a phone?", "Most overrated feature on a phone?"],
  ["Worst social media platform?", "Most addictive social media platform?"],
  ["Best thing about working from home?", "Worst thing about working from home?"],
  ["Best thing to do on a snow day?", "Worst thing to do on a snow day?"],
  ["Most useless school subject?", "Most useful school subject?"],
  ["Worst type of teacher?", "Best type of teacher?"],
  ["Worst kind of hug?", "Best kind of hug?"],
  ["Worst thing about high school?", "Best thing about high school?"],
  ["Worst gift to give?", "Best gift to give?"],
  ["Worst thing to be famous for?", "Best thing to be famous for?"],
  ["Worst restaurant chain?", "Best restaurant chain?"],
  ["Worst Halloween candy?", "Best Halloween candy?"],
  ["Worst place to break down?", "Worst place to run out of gas?"],
  ["Best place to take a nap?", "Worst place to take a nap?"],
  ["Best invention?", "Worst invention?"],
  ["Best app on your phone?", "Most-used app on your phone?"],
  ["Best way to wake up?", "Worst way to wake up?"],
  ["Worst thing to say in a job interview?", "Worst thing to put on a resume?"],
  ["Worst time to laugh?", "Worst time to cry?"],
  ["Name a smell you love but feel weird about", "Name a smell you hate but kind of like"],
  ["Name something everyone owns but rarely uses", "Name something nobody owns but everyone wants"],
  ["A sound that makes you angry", "A sound that makes you happy"],
  ["What's secretly amazing?", "What's secretly terrible?"],
  ["A household chore you secretly enjoy?", "A household chore you absolutely hate?"],
  ["A city that's overrated?", "A city that's underrated?"],
  ["A word that just sounds dirty", "A word that just sounds funny"],
  ["A weird flex?", "An impressive flex?"],
  ["What would you do with $1 million?", "What would you do with $1000?"],
  ["Favorite thing to spend money on?", "Most regretful purchase?"],
  ["Best thing to do on a Friday night?", "Best thing to do on a Saturday morning?"],
  ["Most romantic gesture?", "Most cringe romantic gesture?"],
  ["Great date for $20?", "Great date for $200?"],
  ["Relationship deal-breaker?", "Relationship deal-maker?"],
  ["Worst thing to text your boss?", "Worst thing to text your mom?"],
  ["Best thing about dating?", "Worst thing about dating?"],
  ["Most attractive personality trait?", "Most attractive physical trait?"],
  ["Your love language?", "Your fight language?"],
  ["Best thing your parents taught you?", "Worst thing your parents taught you?"],
  ["Best thing about being an adult?", "Worst thing about being an adult?"],
  ["A hill you'd die on?", "A hill you'd reluctantly defend?"],
  ["What's overrated in dating?", "What's underrated in dating?"],
  ["Funniest thing to yell in public?", "Scariest thing to yell in public?"],
  ["Worst phobia to have?", "Most useful phobia to have?"],
  ["Easiest way to make a million dollars?", "Easiest way to LOSE a million dollars?"],
  ["Great gift for a stoner?", "Great gift for a foodie?"],
  ["Most useless body part?", "Most overrated body part?"],
  ["Best app to delete first?", "Best app to never delete?"],
  ["Worst kind of hangover?", "Worst kind of food poisoning?"],
  ["Worst dating app match?", "Worst Tinder bio?"],

  // ---------- Random / quirky ----------
  ["Name something you'd find in a kitchen", "Name something you'd find in a bedroom"],
  ["Name a word you can shout in a library and not get kicked out", "Name a word that would get you kicked out of a library"],
  ["An animal you'd want as a pet?", "An animal you'd NEVER want as a pet?"],
  ["A country you'd love to visit?", "A country you'd hate to visit?"],
  ["Great first date idea?", "Terrible first date idea?"],
  ["Something you'd bring on a beach trip?", "Something you'd bring on a camping trip?"],
  ["Something you do when you're bored?", "Something you do when you're stressed?"],
  ["Best way to spend a Saturday night?", "Best way to spend a Sunday morning?"],
  ["Best thing about being single?", "Worst thing about being single?"],
  ["A movie that made you cry?", "A movie that made you laugh out loud?"],
  ["A food that tastes better than it looks?", "A food that looks better than it tastes?"],
  ["What's overrated in general?", "What's underrated in general?"],
  ["Something you're secretly really good at?", "Something you're proudly really bad at?"],
  ["A guilty pleasure song?", "A song you blast in the car?"],
  ["Most useless superpower?", "Most overpowered superpower?"],
  ["A celebrity you'd grab a beer with?", "A celebrity you'd avoid at all costs?"],
  ["Something that brings you peace?", "Something that brings you joy?"],
  ["Something you'd tell your younger self?", "Something you'd warn your younger self about?"],
  ["A skill you wish you had?", "A skill you wish you didn't have?"],
  ["A book you actually finished?", "A book you pretended to finish?"],
  ["A song you've heard way too many times?", "A song you'll never get sick of?"],
  ["Best thing to do during a power outage?", "Worst thing to do during a power outage?"],
  ["Something that always makes you laugh?", "Something that always makes you cringe?"],
  ["What's your hot take?", "What's your cold take?"],
  ["Conspiracy theory you kinda believe?", "Conspiracy theory that's obviously fake?"],
  ["A trend you're glad died?", "A trend that should come back?"],
  ["Most useful thing in your bag right now?", "Most random thing in your bag right now?"],
  ["A skill from a movie you wish you had?", "A skill from a video game you wish you had?"],
  ["Best place to people-watch?", "Worst place to people-watch?"],
  ["Worst smell in a car?", "Worst smell in a fridge?"],
  ["Worst place to lose your phone?", "Worst place to lose your wallet?"],
  ["Best feeling after a long day?", "Best feeling after a workout?"],
  ["Worst chore?", "Most satisfying chore?"],
  ["A great Christmas gift?", "A terrible Christmas gift?"],
  ["A great comeback?", "A weak comeback?"],
  ["Best lie to escape a date?", "Best lie to get out of work?"],
  ["What's a major ick?", "What's a forgivable flaw?"],
  ["A small thing that ruins your day?", "A small thing that makes your day?"],
  ["What's worth waiting in line for?", "What's NOT worth waiting in line for?"],
  ["What's the most '80s thing?", "What's the most 2000s thing?"],
  ["A song everyone pretends to like?", "A song everyone pretends to hate?"],
  ["Worst thing to step on barefoot?", "Worst thing to find in your shoe?"],
  ["A great prank?", "A prank that would get you punched?"],
  ["A TV character you'd be friends with?", "A TV character you'd avoid?"],
  ["A movie scene that's burned into your brain?", "A movie quote that lives in your head rent-free?"],
  ["Best way to cure a hangover?", "Worst way to cure a hangover?"],
  ["A weird talent?", "A weird skill?"],
  ["Most haunted-looking thing?", "Most cursed-looking thing?"],
  ["Best meme of all time?", "Most overused meme of all time?"],
  ["Best thing to bring to a potluck?", "Worst thing to bring to a potluck?"],
  ["Best thing to do on vacation?", "Worst thing to do on vacation?"],
  ["A place that feels expensive but isn't?", "A place that feels cheap but isn't?"],
  ["What would your villain origin story be?", "What would your hero origin story be?"],
  ["What's a 10/10 morning routine?", "What's a 10/10 night routine?"],
  ["A question that's hard to answer?", "A question that's easy to answer?"],
  ["A great icebreaker?", "A terrible icebreaker?"],
  ["Best emoji?", "Most misused emoji?"],
  ["What's the most American thing?", "What's the most British thing?"],
  ["A food that gets better as leftovers?", "A food that gets WORSE as leftovers?"],
  ["A thing that's bigger than you'd expect?", "A thing that's smaller than you'd expect?"],
  ["A noise pets make that's adorable?", "A noise pets make that's terrifying?"],
  ["A scary movie you actually finished?", "A scary movie you couldn't finish?"],
  ["A lie everyone tells?", "A truth nobody admits?"],
  ["Most random thing in your fridge?", "Most random thing in your bathroom?"],
  ["What's a surprisingly good combo?", "What's a surprisingly bad combo?"],
  ["The best smell of childhood?", "The worst smell of childhood?"],
  ["Something only kids enjoy?", "Something only adults enjoy?"],
  ["A place that's better at night?", "A place that's better in the morning?"],
  ["A song that should be the national anthem?", "A song that should be banned?"],
  ["A great wedding song?", "A terrible wedding song?"],
  ["Best thing to do when it rains?", "Worst thing to do when it rains?"],
  ["A career that pays too much?", "A career that pays too little?"],
  ["What's a subtle flex?", "What's an obvious flex?"],
  ["Something everyone secretly does?", "Something nobody admits to doing?"],
  ["Best free thing in life?", "Best thing money CAN buy?"],
  ["A nice surprise?", "An unwelcome surprise?"],
  ["Best smell after rain?", "Best smell on a fall morning?"],
  ["A thing you can never have too much of?", "A thing you can definitely have too much of?"],
  ["Best thing in a vending machine?", "Worst thing in a vending machine?"],
  ["A name that's aging well?", "A name that's aging poorly?"],
  ["A great party trick?", "A bad party trick?"],
  ["Best thing about your hometown?", "Worst thing about your hometown?"],
  ["What's the move tonight?", "What's the move tomorrow?"],
  ["A 'main character' move?", "An 'NPC' move?"],
  ["Most cinematic moment?", "Most cringe moment?"],
  ["A great wingman line?", "A line that ruins your wingman?"],
  ["A flex on Instagram?", "A flex on LinkedIn?"],
  ["A great DM opener?", "A horrible DM opener?"],
  ["A great gift for yourself?", "A great gift for your enemy?"],
  ["A guilty pleasure show?", "A guilty pleasure snack?"],
  ["Something you'd never share with friends?", "Something you'd never share with family?"],
  ["A dream wedding venue?", "A nightmare wedding venue?"],
  ["A fight you'd win?", "A fight you'd lose?"],
  ["A movie you'd live inside?", "A movie you'd never want to live inside?"],
];
